services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
      - "3001:3001"
    environment:
      - FASTAPI_APP=llm:app # Ensure your app file and object names are correct
      
